version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
    - MONGODB_URI=${MONGODB_URI}
    - JWT_SECRET=${JWT_SECRET}
    - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    - FASTAPI_URL=${FASTAPI_URL}

    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "5173:5173"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  fastapi:
    image: python:3.11-slim
    # placeholder - expect you to dockerize the fastapi service separately
    command: ["sleep", "infinity"]

volumes:
  mongo-data:
